Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,9 +14,14 @@ jobs:
           node-version: 19
           cache: npm
       - name: install dependencies
-        run: npm ci
-      - name: run tests 
-        run: |
-          npm run test || true
-      - name: create test report
-        run: nyc report --reporter=lcov --reporter=text-lcov      
+        run: npm ci 
+      - name: Run tests
+        run: npm run test || echo "Tests failed, but continuing..."
+      - name: Create test report
+        run: npx nyc report --reporter=lcov --reporter=text-lcov || echo "Failed to create test report, but continuing..."    
+      - name: Coveralls
+        uses: coverallsapp/github-action@v2
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+    env:
+      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}	
